trigger:
  branches:
    include:
      - main

variables:
  # Variables de entorno
  ACR_NAME: 'ACRS6JoelArias'  
  IMAGE_NAME: 's6-joel-arias-nginx'  
  SERVICE_CONNECTION_NAME: 'SConnectS6Joel'  
  
jobs:
- job: BuildAndPush
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Checkout@1
    displayName: 'Descargar repositorio'

  - script: |
      ls -R my-repo/docker
    displayName: 'Verificar archivos en my-repo/docker'

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      containerRegistry: '$(SERVICE_CONNECTION_NAME)'
      repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
      dockerfile: 'my-repo/docker/Dockerfile'  # Ruta específica
      tags: |
        latest
    displayName: 'Build and Push Docker Image'
