trigger:
  branches:
    include:
      - main

variables:
  ACR_NAME: 'ACRS6JoelArias'  
  IMAGE_NAME: 's6-joel-arias-nginx'  
  SERVICE_CONNECTION_NAME: 'SConnectS6Joel'  
  
jobs:
- job: BuildAndPush
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      containerRegistry: '$(SERVICE_CONNECTION_NAME)'
      repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
      dockerfile: '**/Dockerfile'
      tags: |
        latest
      displayName: 'Build and Push Docker Image'